INSERT INTO "Genres" ("Name") VALUES ('Action');
INSERT INTO "Genres" ("Name") VALUES ('Drama');
INSERT INTO "Genres" ("Name") VALUES ('Science Fiction');

INSERT INTO "Books" ("UserId", "Title", "Author", "PublishDate", "Genre", "ISBN", "Location", "Image_url", "Description") VALUES ('a3458344-70c1-448c-929a-86dc295c2b4b', 'No Place Like Here', 'Christina June', '2007-05-22', 1, '0-5562-0702-5', 'Lebanon', 'https://i.pinimg.com/236x/0c/ee/7e/0cee7e54fda8ac99ec11459448e89c7d.jpg', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque eu vulputate mi, quis elementum lectus. Phasellus vestibulum dapibus dictum. Suspendisse eu dolor auctor, placerat velit non, tincidunt dolor. Ut malesuada in justo et volutpat. In id ex neque. Duis rutrum tempus arcu');
INSERT INTO "Books" ("UserId", "Title", "Author", "PublishDate", "Genre", "ISBN", "Location", "Image_url", "Description")  VALUES ('a3458344-70c1-448c-929a-86dc295c2b4b', 'A Million To One', 'Tony Faggioli', '2009-01-26', 1, '0-6170-3369-2', 'Lebanon', 'https://www.designforwriters.com/wp-content/uploads/2017/10/design-for-writers-book-cover-tf-2-a-million-to-one.jpg', 'eu fringilla odio porta vel. Curabitur egestas, leo quis elementum faucibus, dui tortor bibendum magna, ut luctus elit tortor vel urna. Mauris molestie eget erat id mollis. ');
INSERT INTO "Books" ("UserId", "Title", "Author", "PublishDate", "Genre", "ISBN", "Location", "Image_url", "Description") VALUES ('a3458344-70c1-448c-929a-86dc295c2b4b', 'Frankestein', 'Mark Shelly', '2002-12-19', 3, '0-6202-7967-2', 'Lebanon', 'https://i.pinimg.com/564x/f9/8e/2d/f98e2d661445620266c0855d418aab71.jpg', 'Nulla facilisi. Donec egestas enim eget interdum pulvinar. Duis eu massa congue, ultricies purus vitae, venenatis odio. Quisque mi odio, volutpat bibendum tortor ac, vehicula consequat velit.');
INSERT INTO "Books" ("UserId", "Title", "Author", "PublishDate", "Genre", "ISBN", "Location", "Image_url", "Description") VALUES ('a3458344-70c1-448c-929a-86dc295c2b4b', 'A Little Princess', 'Frances Hodgson Burnett', '2002-12-19', 1,'0-6969-3604-6', 'Lebanon', 'https://alysbcohen.files.wordpress.com/2015/01/little-princess-book-cover.jpg', 'Praesent egestas tortor et mi egestas vehicula. Maecenas fermentum enim lectus, et finibus diam condimentum vel. Vivamus imperdiet aliquam tellus, sed ultrices odio pharetra nec. In hac habitasse platea dictumst. ');
INSERT INTO "Books" ("UserId", "Title", "Author", "PublishDate", "Genre", "ISBN", "Location", "Image_url", "Description") VALUES ('a3458344-70c1-448c-929a-86dc295c2b4b', 'Bird By Bird', 'Anne Lamott', '2010-01-20', 1, '0-8743-7007-8', 'Lebanon', 'https://talkingwriting.com//sites/default/files/Bird-by-Bird-image1.jpg', 'Suspendisse viverra, quam nec ornare dignissim, ipsum massa tristique purus, elementum vestibulum mauris tortor ac sapien. Sed semper nec orci ac dictum. Suspendisse convallis scelerisque eleifend. Duis consequat erat augue, et ultricies tellus molestie ac. Donec ut nunc justo. Morbi in molestie tortor. Morbi libero lacus,');
INSERT INTO "Books" ("UserId", "Title", "Author", "PublishDate", "Genre", "ISBN", "Location", "Image_url", "Description") VALUES ('a3458344-70c1-448c-929a-86dc295c2b4b', 'Girl At War', 'Sara Novic', '2007-06-11', 2, '0-3751-7374-9', 'Lebanon', 'https://d.gr-assets.com/books/1414348859l/23209971.jpg', 'Suspendisse at augue commodo, pulvinar sapien in, finibus massa. Nunc euismod quis tortor sit amet eleifend. Praesent consequat augue eget vehicula ultrices. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris efficitur a massa vel luctus.');
